CREATE DATABASE chs;

use chs;

CREATE TABLE users (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(30) NOT NULL, apellido1 VARCHAR(30) NOT NULL, apellido2 VARCHAR(30), contrasena VARCHAR(80) NOT NULL, correo VARCHAR(50) NOT NULL, activo boolean NOT NULL);

CREATE TABLE imagenes (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, hash VARCHAR(80) NOT NULL, iduser INT(11) NOT NULL);
